blank_issues_enabled: false
contact_links:
  - name: QQ group
    url: https://qm.qq.com/q/dhUDlWaCvS
    about: Join BetterRailwaySystem交流群, QQ group 1062170420.
  - name: Discord
    url: https://discord.gg/ufByCWBcNF
    about: Join the Discord server for chat and support.
