blank_issues_enabled: false
contact_links:
  - name: QQ group
    url: https://qm.qq.com/q/1062170420
    about: Join the QQ group 1062170420 for chat and support.
  - name: Discord
    url: https://discord.gg/ufByCWBcNF
    about: Join the Discord server for chat and support.
